name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        if [ -f "yarn.lock" ]; then
          yarn install --frozen-lockfile
        else
          npm ci
        fi

    - name: Build
      run: npm run build  # Adjust this command based on your build process

    - name: Test
      run: npm test  # Adjust this command based on your test process
